In [1]:
import pandas as pd 
import numpy as np


In [1]:
import sys
print(sys.executable)


/home/ishido/Desktop/Aj/New proj/HELP extend/environment/venv/bin/python


In [2]:
PPI_edges = pd.read_csv('../data/processed/kidney_PPI_final.csv')

In [3]:
labels = pd.read_csv('../data/processed/Crispr_labels_final.csv')

In [4]:
expressions = pd.read_csv('../data/processed/Kidney_expression_final.csv')

In [5]:
mutations = pd.read_csv('../data/processed/Kidney_mutations_final.csv')

In [6]:
common = set(expressions['ModelID']) & set(labels['ModelID'])
len(common)

32

In [7]:
len(common & set(mutations['ModelID']))



32

In [8]:
expressions = expressions[expressions['ModelID'].isin(common)]
mutations = mutations[mutations['ModelID'].isin(common)]
labels = labels[labels['ModelID'].isin(common)]


In [9]:
expressions.shape

(32, 18360)

In [10]:
mutations.shape

(32, 17150)

In [11]:
labels.shape

(32, 17864)

In [13]:
expressions.to_csv("../data/Final/expressions.csv",index=False)

In [14]:
mutations.to_csv("../data/Final/mutations.csv",index=False)

In [15]:
labels.to_csv("../data/Final/labels.csv",index = False)

In [14]:
exprxn = pd.read_csv("../data/processed/Kidney_expression_final.csv")

In [ ]:
exprxn

,ModelID,TSPAN6,TNMD,DPM1,SCYL3,FIRRM,FGR,CFH,FUCA2,GCLC,...,CCDC39,UPK3BL2,ARHGAP11B,ASDURF,DERPC,NOTCH2NLC,H3C2,NPBWR1,ACTL10,PRRC2B
0,ACH-002438,4.336705,0.000000,6.879387,2.262824,3.256491,0.000000,2.253926,6.895436,3.470992,...,0.456676,1.819562,1.553459,2.227735,4.147062,3.458790,0.255362,0.024008,0.984538,4.949465
1,ACH-000792,3.500318,0.000000,6.572009,1.812749,3.596935,0.093977,0.508347,6.694044,4.797376,...,2.089447,1.716346,3.057705,0.701833,2.096609,4.620088,0.659900,0.271451,0.393398,5.311536
2,ACH-000317,3.551270,0.000000,6.121229,2.008612,2.559269,0.079367,4.279278,5.128755,2.962580,...,2.262349,3.567679,2.142609,0.966736,4.076764,3.735825,0.193359,0.179049,1.816018,5.852713
3,ACH-000313,3.815002,0.000000,5.790728,2.040068,2.488430,0.214781,6.010695,5.732893,4.818355,...,2.574240,3.410553,2.816823,1.277265,3.605435,4.499100,0.512084,0.085998,1.043813,6.262553
4,ACH-001398,4.363234,0.000000,7.044121,1.939708,3.001002,0.000000,5.802126,6.052003,4.781118,...,0.553027,3.737059,1.613800,2.627845,3.619706,4.617275,0.563187,0.495400,1.353459,4.534995
5,ACH-001200,2.745519,0.000000,5.975256,2.504030,4.151461,0.000000,1.761885,6.981065,3.944868,...,0.788148,4.487776,2.436034,3.444336,2.297133,3.649466,0.336071,0.000000,0.246098,6.068778
6,ACH-001688,4.304204,0.000000,4.627689,2.064835,2.407018,0.006383,1.377835,4.547573,2.267518,...,0.162523,5.947512,1.446981,0.126736,3.240294,3.480007,0.507673,0.154114,1.592536,3.702148
7,ACH-000428,3.718690,0.000000,6.672397,1.969410,3.263720,0.080280,1.697133,6.718595,4.281602,...,1.354746,2.313019,1.972579,2.292063,4.185367,2.900196,0.946023,1.069998,0.859691,5.345623
8,ACH-000684,2.841025,0.000000,6.861521,2.007027,4.000171,0.010151,4.765726,7.312003,3.254236,...,0.689704,2.508353,1.381533,0.993621,3.410581,4.150227,0.341549,0.180875,1.258151,2.091297
9,ACH-000429,3.656382,0.000000,6.082187,2.089559,2.811607,0.084331,4.963067,4.424459,3.808920,...,1.372239,3.478972,3.165299,2.005874,2.159413,2.163183,0.761976,0.099411,0.272465,3.332303


In [15]:
ppi = pd.read_csv("../data/processed/kidney_PPI_final.csv")
ppi

,A,B,combined_score,coexpression
0,MAP2K4,FLNC,2,0.285217
1,FNTA,ACVR1,2,0.014917
2,GATA2,PML,2,-0.098040
3,RPA2,STAT3,2,0.350444
4,ARF1,GGA3,2,0.304046
...,...,...,...,...
1528071,LAMA2,FBLN2,1,0.301295
1528072,BMP1,DSPP,1,-0.197264
1528073,SNAI1,LOXL1,1,0.159567
1528074,FBLN1,COL18A1,2,0.070642


In [16]:
exprxn_values = exprxn.drop('ModelID',axis=1)

In [17]:
exprxn_values

,TSPAN6,TNMD,DPM1,SCYL3,FIRRM,FGR,CFH,FUCA2,GCLC,NFYA,...,CCDC39,UPK3BL2,ARHGAP11B,ASDURF,DERPC,NOTCH2NLC,H3C2,NPBWR1,ACTL10,PRRC2B
0,4.336705,0.000000,6.879387,2.262824,3.256491,0.000000,2.253926,6.895436,3.470992,4.308375,...,0.456676,1.819562,1.553459,2.227735,4.147062,3.458790,0.255362,0.024008,0.984538,4.949465
1,3.500318,0.000000,6.572009,1.812749,3.596935,0.093977,0.508347,6.694044,4.797376,7.350621,...,2.089447,1.716346,3.057705,0.701833,2.096609,4.620088,0.659900,0.271451,0.393398,5.311536
2,3.551270,0.000000,6.121229,2.008612,2.559269,0.079367,4.279278,5.128755,2.962580,2.837528,...,2.262349,3.567679,2.142609,0.966736,4.076764,3.735825,0.193359,0.179049,1.816018,5.852713
3,3.815002,0.000000,5.790728,2.040068,2.488430,0.214781,6.010695,5.732893,4.818355,3.799181,...,2.574240,3.410553,2.816823,1.277265,3.605435,4.499100,0.512084,0.085998,1.043813,6.262553
4,4.363234,0.000000,7.044121,1.939708,3.001002,0.000000,5.802126,6.052003,4.781118,3.327125,...,0.553027,3.737059,1.613800,2.627845,3.619706,4.617275,0.563187,0.495400,1.353459,4.534995
5,2.745519,0.000000,5.975256,2.504030,4.151461,0.000000,1.761885,6.981065,3.944868,3.833649,...,0.788148,4.487776,2.436034,3.444336,2.297133,3.649466,0.336071,0.000000,0.246098,6.068778
6,4.304204,0.000000,4.627689,2.064835,2.407018,0.006383,1.377835,4.547573,2.267518,2.670408,...,0.162523,5.947512,1.446981,0.126736,3.240294,3.480007,0.507673,0.154114,1.592536,3.702148
7,3.718690,0.000000,6.672397,1.969410,3.263720,0.080280,1.697133,6.718595,4.281602,3.401005,...,1.354746,2.313019,1.972579,2.292063,4.185367,2.900196,0.946023,1.069998,0.859691,5.345623
8,2.841025,0.000000,6.861521,2.007027,4.000171,0.010151,4.765726,7.312003,3.254236,3.313880,...,0.689704,2.508353,1.381533,0.993621,3.410581,4.150227,0.341549,0.180875,1.258151,2.091297
9,3.656382,0.000000,6.082187,2.089559,2.811607,0.084331,4.963067,4.424459,3.808920,2.636047,...,1.372239,3.478972,3.165299,2.005874,2.159413,2.163183,0.761976,0.099411,0.272465,3.332303


In [18]:
A_values = exprxn_values[ppi['A']].values
B_values = exprxn_values[ppi['B']].values

In [ ]:
A_values

array([[4.39719373, 6.08170179, 0.89110573, ..., 0.9523455 , 8.11163127,
        8.11163127],
       [3.61948344, 5.45035018, 3.5268826 , ..., 2.67617487, 0.64346742,
        0.64346742],
       [3.8047867 , 5.98831204, 0.48925313, ..., 1.18649422, 6.39804248,
        6.39804248],
       ...,
       [4.1561377 , 6.07386949, 0.01679724, ..., 1.25807263, 3.61963603,
        3.61963603],
       [2.84241572, 5.53107885, 0.16766236, ..., 0.69729165, 0.05463735,
        0.05463735],
       [4.39774821, 5.76531992, 0.12760291, ..., 0.75017856, 2.95254604,
        2.95254604]], shape=(53, 1528076))

In [19]:
A_values.nbytes / 1e9


0.647904224

In [20]:
A_Centered = A_values - A_values.mean(axis=0)
B_Centered = B_values - B_values.mean(axis=0)

In [21]:
A_Centered

array([[ 0.39725762,  0.33867687, -0.76052614, ..., -1.04539738,
         4.2335739 ,  4.2335739 ],
       [-0.38045267, -0.29267473,  1.87525073, ...,  0.67843199,
        -3.23458995, -3.23458995],
       [-0.19514941,  0.24528712, -1.16237874, ..., -0.81124866,
         2.51998511,  2.51998511],
       ...,
       [ 0.15620159,  0.33084458, -1.63483463, ..., -0.73967025,
        -0.25842133, -0.25842133],
       [-1.15752039, -0.21194606, -1.48396951, ..., -1.30045122,
        -3.82342001, -3.82342001],
       [ 0.3978121 ,  0.022295  , -1.52402896, ..., -1.24756431,
        -0.92551132, -0.92551132]], shape=(53, 1528076))

In [22]:
num = (A_Centered * B_Centered).sum(axis=0)

In [23]:
denom = np.sqrt((A_Centered**2).sum(axis=0) * (B_Centered**2).sum(axis=0))


In [24]:
coexpression = num / denom
coexpression[10:]


/tmp/ipykernel_12888/1158407507.py:1: RuntimeWarning: invalid value encountered in divide
  coexpression = num / denom


array([ 0.52811553,  0.01698002, -0.07952349, ...,  0.15956676,
        0.07064193,  0.31386795], shape=(1528066,))

In [25]:
np.isnan(coexpression).sum()


np.int64(7405)

In [26]:
coexpression = np.nan_to_num(coexpression, nan=0.0)


In [27]:
coexpression.shape


(1528076,)

In [28]:
np.isnan(coexpression).sum()


np.int64(0)

In [29]:
ppi['coexpression'] = coexpression
ppi.head()

,A,B,combined_score,coexpression
0,MAP2K4,FLNC,2,0.285217
1,FNTA,ACVR1,2,0.014917
2,GATA2,PML,2,-0.098040
3,RPA2,STAT3,2,0.350444
4,ARF1,GGA3,2,0.304046


In [ ]:
ppi.to_csv('../data/processed/kidney_PPI_final.csv', index=False)
